name: dbt_run_streamline_dexalot_history
run-name: dbt_run_streamline_dexalot_history

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@main
    with:
      command_name: Run Chainhead Models
      command: |
        dbt run --vars '{"STREAMLINE_INVOKE_STREAMS":True}' -m "avalanche_models,tag:streamline_dexalot_complete" "avalanche_models,tag:streamline_dexalot_history"
    secrets: inherit