name: dbt_run_streamline_dexalot_non_realtime
run-name: dbt_run_streamline_dexalot_non_realtime

on:
  workflow_dispatch:
    branches:
      - "main"
  schedule:
    - cron: '5 * * * *'

env:
  DBT_PROFILES_DIR: ./

  ACCOUNT: "${{ vars.ACCOUNT }}"
  ROLE: "${{ vars.ROLE }}"
  USER: "${{ vars.USER }}"
  PASSWORD: "${{ secrets.PASSWORD }}"
  REGION: "${{ vars.REGION }}"
  DATABASE: "${{ vars.DATABASE }}"
  WAREHOUSE: "${{ vars.WAREHOUSE }}"
  SCHEMA: "${{ vars.SCHEMA }}"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@pre-release/v4-beta
    with:
      command_name: Run Chainhead Models
      command: |
        dbt run -m "avalanche_models,tag:dexalot_non_realtime"
    secrets: inherit