name: dbt_run_scheduled_dexalot_main
run-name: dbt_run_scheduled_dexalot_main

on:
  workflow_dispatch:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}

jobs:
  called_workflow_template:
    uses: FlipsideCrypto/fsc-evm/.github/workflows/dbt_run_template.yml@main
    with:
      command_name: Run Chainhead Models
      command: |
        dbt run -m "avalanche_models,tag:dexalot_main"
    secrets: inherit