name: Slack Notification
on:
  workflow_call:
    inputs:
      workflow_name:
        description: 'Name of the workflow'
        required: false
        type: string
        default: ''
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: workflow_prod
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Format optimized for multi-repository deployment
          payload: |
            {
              "text": "⚠️ *Workflow Failed*: ${{ inputs.workflow_name || github.workflow }}\n*Repository*: ${{ github.repository }}\n*Branch*: ${{ github.ref_name }}\n*Workflow URL*: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}