name: Slack Notification
on:
  workflow_call:
    inputs:
      workflow_name:
        description: 'Name of the workflow'
        required: false
        type: string
        default: ''
    secrets:
      SLACK_WEBHOOK_URL:
        required: true

jobs:
  notify:
    runs-on: ubuntu-latest
    environment: workflow_prod
    steps:
      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": ":x: *${{ inputs.workflow_name || github.workflow }}* failed in *${{ github.repository }}*\n <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View workflow run>",
              "attachments": [
                {
                  "color": "#FF0000",
                  "title": "Workflow Failed: ${{ inputs.workflow_name || github.workflow }}",
                  "title_link": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "Branch",
                      "value": "${{ github.ref_name }}",
                      "short": true
                    }
                  ],
                  "footer": "GitHub Actions"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}