version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'AVALANCHE' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
  - name: ethereum
    database: ethereum
    schema: core
    tables:
      - name: fact_hourly_token_prices
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables:
      - name: node_mapping
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: apis_keys
      - name: address_labels
      - name: token_prices_priority_hourly
      - name: asset_metadata_priority
      - name: token_prices_all_providers_hourly
      - name: asset_metadata_all_providers
      - name: near_address_encoded
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "AVALANCHE_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "AVALANCHE" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceBlockByNumber
      - name: decoded_logs
      - name: confirm_blocks
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: avalanche_silver
    database: avalanche
    schema: silver
    tables:
      - name: verified_abis
  - name: avalanche_bronze_api
    database: avalanche
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: avalanche
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
