version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: avalanche_blocks
      - name: avalanche_txs
  - name: crosschain
    database: crosschain
    schema: core
    tables:
      - name: address_labels
  - name: ethereum 
    database: ethereum
    schema: core 
    tables: 
      - name: fact_hourly_token_prices
  - name: avalanche_pools
    database: avalanche
    schema: bronze
    tables:
      - name: SUSHI_DIM_DEX_POOLS
      - name: SUSHI_DIM_KASHI_PAIRS
  - name: prices
    database: FLIPSIDE_PROD_DB
    schema: SILVER
    tables:
      - name: prices_v2
  - name: streamline_crosschain
    database: streamline
    schema: crosschain
    tables: 
      - name: node_mapping
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: apis_keys

