version: 2

sources:
  - name: prod
    database: chainwalkers
    schema: prod
    tables:
      - name: avalanche_blocks
      - name: avalanche_txs
  - name: crosschain
    database: flipside_prod_db
    schema: crosschain
    tables:
      - name: address_labels
  - name: ethereum 
    database: ethereum
    schema: core 
    tables: 
      - name: fact_hourly_token_prices