version: 2

sources:
  - name: crosschain
    database: "{{ 'crosschain' if target.database == 'AVALANCHE' else 'crosschain_dev' }}"
    schema: core
    tables:
      - name: dim_labels
  - name: crosschain_silver
    database: crosschain
    schema: silver
    tables:
      - name: address_labels
      - name: near_address_encoded
      - name: labels_combined
      - name: complete_token_asset_metadata
      - name: complete_token_prices
      - name: complete_provider_asset_metadata
      - name: complete_provider_prices
      - name: complete_native_asset_metadata
      - name: complete_native_prices
      - name: number_sequence
  - name: bronze_streamline
    database: streamline
    schema: |
      {{ "AVALANCHE_DEV" if var("STREAMLINE_USE_DEV_FOR_EXTERNAL_TABLES", False) else "AVALANCHE" }}
    tables:
      - name: receipts
      - name: blocks
      - name: transactions
      - name: debug_traceBlockByNumber
      - name: decoded_logs
      - name: confirm_blocks
      - name: dexalot_blocks
      - name: dexalot_transactions
      - name: dexalot_receipts
      - name: dexalot_traces
      - name: dexalot_confirm_blocks
  - name: crosschain_public
    database: crosschain
    schema: bronze_public
    tables:
      - name: user_abis
  - name: avalanche_silver
    database: avalanche
    schema: silver
    tables:
      - name: verified_abis
  - name: avalanche_bronze_api
    database: avalanche
    schema: bronze_api
    tables:
      - name: contract_abis
  - name: github_actions
    database: avalanche
    schema: github_actions
    tables:
      - name: workflows
  - name: external_gold_defillama
    database: external
    schema: defillama
    tables:
      - name: dim_chains
